/**
 * Add researched skills to the database.
 *
 * Workflow:
 *   1. npx tsx scripts/add-new-skills.ts  — insert skeleton data
 *   2. npx tsx scripts/enrich-skills.ts   — Gemini generates description_ko, summary, usage_guide
 *
 * description_ko를 비워두면 enrich 스크립트가 자동으로 대상에 포함시킴.
 */

import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import { resolve } from 'path';

// Load .env.local
try {
  const envPath = resolve(import.meta.dirname ?? __dirname, '..', '.env.local');
  const envContent = readFileSync(envPath, 'utf-8');
  for (const line of envContent.split('\n')) {
    const match = line.match(/^([^#=]+)=(.*)$/);
    if (match) {
      const [, key, value] = match;
      if (!process.env[key.trim()]) {
        process.env[key.trim()] = value.trim();
      }
    }
  }
} catch {
  // CI
}

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

interface NewSkill {
  readonly slug: string;
  readonly name: string;
  readonly name_ko: string;
  readonly github_url: string;
  readonly github_owner: string;
  readonly github_repo: string;
  readonly description_en: string;
  readonly category_id: string;
  readonly tags: readonly string[];
  readonly stars: number;
}

const newSkills: readonly NewSkill[] = [
  { slug: 'cherryhq-cherry-studio', name: 'Cherry Studio', name_ko: 'Cherry Studio', github_url: 'https://github.com/CherryHQ/cherry-studio', github_owner: 'CherryHQ', github_repo: 'cherry-studio', description_en: 'AI productivity studio with smart chat, autonomous agents, and 300+ assistants.', category_id: 'productivity', tags: ['agent', 'productivity', 'automation'], stars: 39897 },
  { slug: 'code-yeongyu-oh-my-opencode', name: 'Oh My Opencode', name_ko: 'Oh My Opencode', github_url: 'https://github.com/code-yeongyu/oh-my-opencode', github_owner: 'code-yeongyu', github_repo: 'oh-my-opencode', description_en: 'The best agent harness for OpenCode with enhanced configuration and skills.', category_id: 'development', tags: ['claude-code', 'agent', 'development'], stars: 31999 },
  { slug: 'oraios-serena', name: 'Serena', name_ko: 'Serena', github_url: 'https://github.com/oraios/serena', github_owner: 'oraios', github_repo: 'serena', description_en: 'A powerful coding agent toolkit providing semantic retrieval and editing capabilities.', category_id: 'development', tags: ['claude-code', 'agent', 'development'], stars: 20326 },
  { slug: 'steveyegge-beads', name: 'Beads', name_ko: 'Beads', github_url: 'https://github.com/steveyegge/beads', github_owner: 'steveyegge', github_repo: 'beads', description_en: 'Beads - A memory upgrade for your coding agent.', category_id: 'productivity', tags: ['claude-code', 'memory', 'productivity'], stars: 16556 },
  { slug: 'blader-humanizer', name: 'Humanizer', name_ko: 'Humanizer', github_url: 'https://github.com/blader/humanizer', github_owner: 'blader', github_repo: 'humanizer', description_en: 'Claude Code skill that removes signs of AI-generated writing from text.', category_id: 'docs', tags: ['skill', 'writing', 'productivity'], stars: 4906 },
  { slug: 'op7418-humanizer-zh', name: 'Humanizer ZH', name_ko: 'Humanizer 중국어', github_url: 'https://github.com/op7418/Humanizer-zh', github_owner: 'op7418', github_repo: 'Humanizer-zh', description_en: 'Chinese version of Humanizer. Claude Code Skills to remove AI-generated traces from text.', category_id: 'docs', tags: ['skill', 'writing', 'productivity'], stars: 2993 },
  { slug: 'khazp-vibe-coding-prompt-template', name: 'Vibe Coding Prompt Template', name_ko: 'Vibe 코딩 프롬프트 템플릿', github_url: 'https://github.com/KhazP/vibe-coding-prompt-template', github_owner: 'KhazP', github_repo: 'vibe-coding-prompt-template', description_en: 'Templates and workflow for generating PRDs, Tech Designs, and MVP using LLMs for AI IDEs.', category_id: 'productivity', tags: ['skill', 'productivity', 'automation'], stars: 1781 },
  { slug: 'lst97-claude-code-sub-agents', name: 'Claude Code Sub Agents', name_ko: 'Claude Code 서브에이전트', github_url: 'https://github.com/lst97/claude-code-sub-agents', github_owner: 'lst97', github_repo: 'claude-code-sub-agents', description_en: 'Collection of specialized AI subagents for Claude Code for full-stack development.', category_id: 'development', tags: ['claude-code', 'agent', 'development'], stars: 1410 },
  { slug: 'maxritter-claude-pilot', name: 'Claude Pilot', name_ko: 'Claude Pilot', github_url: 'https://github.com/maxritter/claude-pilot', github_owner: 'maxritter', github_repo: 'claude-pilot', description_en: 'Claude Code is powerful. Pilot makes it reliable with structured workflows and guardrails.', category_id: 'productivity', tags: ['claude-code', 'productivity', 'automation'], stars: 1236 },
  { slug: 'itsmostafa-aws-agent-skills', name: 'AWS Agent Skills', name_ko: 'AWS 에이전트 스킬', github_url: 'https://github.com/itsmostafa/aws-agent-skills', github_owner: 'itsmostafa', github_repo: 'aws-agent-skills', description_en: 'AWS Skills for AI Agents covering cloud infrastructure and services.', category_id: 'devops', tags: ['skill', 'aws', 'development'], stars: 994 },
  { slug: 'ceeon-videocut-skills', name: 'Videocut Skills', name_ko: '비디오 편집 스킬', github_url: 'https://github.com/Ceeon/videocut-skills', github_owner: 'Ceeon', github_repo: 'videocut-skills', description_en: 'Video editing Agent using Claude Code Skills.', category_id: 'productivity', tags: ['skill', 'video', 'automation'], stars: 921 },
  { slug: 'simonw-claude-skills', name: 'Simon W Claude Skills', name_ko: 'Simon W Claude 스킬', github_url: 'https://github.com/simonw/claude-skills', github_owner: 'simonw', github_repo: 'claude-skills', description_en: 'The contents of /mnt/skills in Claude\'s code interpreter environment.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 916 },
  { slug: 'synalinks-synalinks-skills', name: 'Synalinks Skills', name_ko: 'Synalinks 스킬', github_url: 'https://github.com/SynaLinks/synalinks-skills', github_owner: 'SynaLinks', github_repo: 'synalinks-skills', description_en: 'Claude skills for Synalinks OSS framework.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 899 },
  { slug: 'instavm-coderunner', name: 'Coderunner', name_ko: 'Coderunner', github_url: 'https://github.com/instavm/coderunner', github_owner: 'instavm', github_repo: 'coderunner', description_en: 'A secure local sandbox to run LLM-generated code using Apple containers.', category_id: 'devops', tags: ['claude-code', 'docker', 'development'], stars: 781 },
  { slug: 'browserwing-browserwing', name: 'BrowserWing', name_ko: 'BrowserWing', github_url: 'https://github.com/browserwing/browserwing', github_owner: 'browserwing', github_repo: 'browserwing', description_en: 'BrowserWing turns your browser actions into MCP commands or Claude Skill.', category_id: 'productivity', tags: ['skill', 'web', 'automation'], stars: 748 },
  { slug: 'bayramannakov-claude-reflect', name: 'Claude Reflect', name_ko: 'Claude Reflect', github_url: 'https://github.com/BayramAnnakov/claude-reflect', github_owner: 'BayramAnnakov', github_repo: 'claude-reflect', description_en: 'A self-learning system for Claude Code that captures corrections and preferences.', category_id: 'productivity', tags: ['claude-code', 'memory', 'productivity'], stars: 690 },
  { slug: 'brownfinesecurity-iothackbot', name: 'IoT HackBot', name_ko: 'IoT HackBot', github_url: 'https://github.com/BrownFineSecurity/iothackbot', github_owner: 'BrownFineSecurity', github_repo: 'iothackbot', description_en: 'IoT HackBot: Claude Skills and tooling for hybrid IoT pentesting.', category_id: 'testing', tags: ['skill', 'security', 'development'], stars: 639 },
  { slug: 'yzfly-douyin-mcp-server', name: 'Douyin MCP Server', name_ko: '도우인 MCP 서버', github_url: 'https://github.com/yzfly/douyin-mcp-server', github_owner: 'yzfly', github_repo: 'douyin-mcp-server', description_en: 'Extract Douyin watermark-free video links and transcripts. MCP server and Claude skill.', category_id: 'productivity', tags: ['skill', 'video', 'automation'], stars: 602 },
  { slug: 'skills-directory-skill-codex', name: 'Skill Codex', name_ko: 'Skill Codex', github_url: 'https://github.com/skills-directory/skill-codex', github_owner: 'skills-directory', github_repo: 'skill-codex', description_en: 'A Claude Code skill to delegate prompts to Codex AI agent.', category_id: 'productivity', tags: ['skill', 'agent', 'productivity'], stars: 595 },
  { slug: 'daymade-claude-code-skills', name: 'Daymade Claude Skills', name_ko: 'Daymade Claude 스킬', github_url: 'https://github.com/daymade/claude-code-skills', github_owner: 'daymade', github_repo: 'claude-code-skills', description_en: 'Professional Claude Code skills marketplace featuring production-ready skills.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 586 },
  { slug: 'wshuyi-x-article-publisher-skill', name: 'X Article Publisher', name_ko: 'X 아티클 퍼블리셔', github_url: 'https://github.com/wshuyi/x-article-publisher-skill', github_owner: 'wshuyi', github_repo: 'x-article-publisher-skill', description_en: 'Claude Code skill for publishing Markdown articles to X (Twitter) Articles.', category_id: 'docs', tags: ['skill', 'writing', 'productivity'], stars: 585 },
  { slug: 'addyosmani-web-quality-skills', name: 'Web Quality Skills', name_ko: '웹 품질 스킬', github_url: 'https://github.com/addyosmani/web-quality-skills', github_owner: 'addyosmani', github_repo: 'web-quality-skills', description_en: 'Agent Skills for optimizing web quality based on Lighthouse and Core Web Vitals.', category_id: 'development', tags: ['skill', 'web', 'development'], stars: 551 },
  { slug: 'tripleyak-skillforge', name: 'SkillForge', name_ko: 'SkillForge', github_url: 'https://github.com/tripleyak/SkillForge', github_owner: 'tripleyak', github_repo: 'SkillForge', description_en: 'The ultimate meta-skill for generating best-in-class Claude Code skills.', category_id: 'productivity', tags: ['skill', 'productivity', 'automation'], stars: 508 },
  { slug: 'rokpiy-auto-commenter', name: 'Auto Commenter', name_ko: 'Auto Commenter', github_url: 'https://github.com/rokpiy/auto-commenter', github_owner: 'rokpiy', github_repo: 'auto-commenter', description_en: 'A Claude skill that automatically posts personalized comments in target communities.', category_id: 'productivity', tags: ['skill', 'automation', 'productivity'], stars: 505 },
  { slug: 'zscole-adversarial-spec', name: 'Adversarial Spec', name_ko: 'Adversarial Spec', github_url: 'https://github.com/zscole/adversarial-spec', github_owner: 'zscole', github_repo: 'adversarial-spec', description_en: 'A Claude Code plugin that iteratively refines product specifications by debating between multiple LLMs.', category_id: 'productivity', tags: ['claude-code', 'agent', 'productivity'], stars: 489 },
  { slug: 'charleswiltgen-axiom', name: 'Axiom', name_ko: 'Axiom', github_url: 'https://github.com/CharlesWiltgen/Axiom', github_owner: 'CharlesWiltgen', github_repo: 'Axiom', description_en: 'Battle-tested Claude Code skills for modern xOS (iOS, iPadOS, watchOS, tvOS) development.', category_id: 'development', tags: ['skill', 'ios', 'development'], stars: 473 },
  { slug: 'vikashloomba-copilot-mcp', name: 'Copilot MCP', name_ko: 'Copilot MCP', github_url: 'https://github.com/VikashLoomba/copilot-mcp', github_owner: 'VikashLoomba', github_repo: 'copilot-mcp', description_en: 'A VSCode extension to find and install Agent Skills and MCP Apps for GitHub Copilot.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 465 },
  { slug: 'geekjourneyx-md2wechat-skill', name: 'MD to WeChat', name_ko: 'MD to WeChat', github_url: 'https://github.com/geekjourneyx/md2wechat-skill', github_owner: 'geekjourneyx', github_repo: 'md2wechat-skill', description_en: 'Write WeChat articles in Markdown, convert to beautiful layout and upload to draft.', category_id: 'docs', tags: ['skill', 'wechat', 'writing'], stars: 447 },
  { slug: 'abubakarsiddik31-claude-skills-collection', name: 'Claude Skills Collection', name_ko: 'Claude 스킬 컬렉션', github_url: 'https://github.com/abubakarsiddik31/claude-skills-collection', github_owner: 'abubakarsiddik31', github_repo: 'claude-skills-collection', description_en: 'A curated collection of official and community-built Claude Skills.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 440 },
  { slug: 'fcakyon-claude-codex-settings', name: 'Claude Codex Settings', name_ko: 'Claude Codex 설정', github_url: 'https://github.com/fcakyon/claude-codex-settings', github_owner: 'fcakyon', github_repo: 'claude-codex-settings', description_en: 'Personal Claude Code and OpenAI Codex setup with battle-tested skills and agents.', category_id: 'development', tags: ['claude-code', 'agent', 'development'], stars: 422 },
  { slug: 'kasperjunge-agent-resources', name: 'Agent Resources', name_ko: 'Agent Resources', github_url: 'https://github.com/kasperjunge/agent-resources', github_owner: 'kasperjunge', github_repo: 'agent-resources', description_en: 'A package manager for AI agents. Install agent skills from GitHub with a single command.', category_id: 'productivity', tags: ['skill', 'agent', 'productivity'], stars: 398 },
  { slug: 'lijigang-ljg-skill-xray-paper', name: 'Paper X-Ray', name_ko: '논문 X-Ray', github_url: 'https://github.com/lijigang/ljg-skill-xray-paper', github_owner: 'lijigang', github_repo: 'ljg-skill-xray-paper', description_en: 'Paper X-Ray - Claude Code Skill for deconstructing academic papers and extracting key insights.', category_id: 'docs', tags: ['skill', 'writing', 'productivity'], stars: 395 },
  { slug: 'dgreenheck-webgpu-claude-skill', name: 'WebGPU Claude Skill', name_ko: 'WebGPU Claude 스킬', github_url: 'https://github.com/dgreenheck/webgpu-claude-skill', github_owner: 'dgreenheck', github_repo: 'webgpu-claude-skill', description_en: 'A Claude skill for developing WebGPU applications with Three.js.', category_id: 'development', tags: ['skill', 'web', 'development'], stars: 378 },
  { slug: 'jlevy-repren', name: 'Repren', name_ko: 'Repren', github_url: 'https://github.com/jlevy/repren', github_owner: 'jlevy', github_repo: 'repren', description_en: 'Power rename/refactor tool with Claude Code skill support.', category_id: 'development', tags: ['skill', 'development', 'tool'], stars: 370 },
  { slug: 'instavm-open-skills', name: 'Open Skills', name_ko: 'Open Skills', github_url: 'https://github.com/instavm/open-skills', github_owner: 'instavm', github_repo: 'open-skills', description_en: 'OpenSkills: Run Claude Skills locally using any LLM.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 370 },
  { slug: 'solana-foundation-solana-dev-skill', name: 'Solana Dev Skill', name_ko: 'Solana 개발 스킬', github_url: 'https://github.com/solana-foundation/solana-dev-skill', github_owner: 'solana-foundation', github_repo: 'solana-dev-skill', description_en: 'Claude Code skill for modern Solana development with best practices.', category_id: 'development', tags: ['skill', 'solana', 'development'], stars: 350 },
  { slug: 'aaronontheweb-dotnet-skills', name: 'Dotnet Skills', name_ko: '.NET 스킬', github_url: 'https://github.com/Aaronontheweb/dotnet-skills', github_owner: 'Aaronontheweb', github_repo: 'dotnet-skills', description_en: 'Claude Code skills and sub-agents for .NET Developers.', category_id: 'development', tags: ['skill', 'dotnet', 'development'], stars: 345 },
  { slug: 'joeseesun-anything-to-notebooklm', name: 'Anything to NotebookLM', name_ko: 'Anything to NotebookLM', github_url: 'https://github.com/joeseesun/anything-to-notebooklm', github_owner: 'joeseesun', github_repo: 'anything-to-notebooklm', description_en: 'Claude Skill: Multi-source content processor for NotebookLM.', category_id: 'docs', tags: ['skill', 'writing', 'productivity'], stars: 340 },
  { slug: 'coleam00-second-brain-skills', name: 'Second Brain Skills', name_ko: 'Second Brain 스킬', github_url: 'https://github.com/coleam00/second-brain-skills', github_owner: 'coleam00', github_repo: 'second-brain-skills', description_en: 'A collection of Claude Skills to turn Claude Code into a Second Brain.', category_id: 'productivity', tags: ['skill', 'memory', 'productivity'], stars: 339 },
  { slug: '23blocks-os-ai-maestro', name: 'AI Maestro', name_ko: 'AI Maestro', github_url: 'https://github.com/23blocks-OS/ai-maestro', github_owner: '23blocks-OS', github_repo: 'ai-maestro', description_en: 'AI Agent Orchestrator with Skills System for memory search, code graph queries.', category_id: 'productivity', tags: ['skill', 'agent', 'memory'], stars: 322 },
  { slug: 'waynesutton-convexskills', name: 'Convex Skills', name_ko: 'Convex 스킬', github_url: 'https://github.com/waynesutton/convexskills', github_owner: 'waynesutton', github_repo: 'convexskills', description_en: 'AI agent skills and templates for building production-ready apps with Convex.', category_id: 'development', tags: ['skill', 'convex', 'development'], stars: 316 },
  { slug: 'k-dense-ai-claude-skills-mcp', name: 'Claude Skills MCP', name_ko: 'Claude Skills MCP', github_url: 'https://github.com/K-Dense-AI/claude-skills-mcp', github_owner: 'K-Dense-AI', github_repo: 'claude-skills-mcp', description_en: 'MCP server for searching and retrieving Claude Agent Skills using vector search.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 316 },
  { slug: 'ailabs-393-ai-labs-claude-skills', name: 'AI Labs Claude Skills', name_ko: 'AI Labs Claude 스킬', github_url: 'https://github.com/ailabs-393/ai-labs-claude-skills', github_owner: 'ailabs-393', github_repo: 'ai-labs-claude-skills', description_en: 'Package for finding and managing Claude skills with easy integration.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 304 },
  { slug: 'axtonliu-smart-illustrator', name: 'Smart Illustrator', name_ko: 'Smart Illustrator', github_url: 'https://github.com/axtonliu/smart-illustrator', github_owner: 'axtonliu', github_repo: 'smart-illustrator', description_en: 'AI-powered article illustrations with intelligent position detection. Claude Code skill.', category_id: 'docs', tags: ['skill', 'writing', 'productivity'], stars: 302 },
  { slug: 'zippoxer-subtask', name: 'Subtask', name_ko: 'Subtask', github_url: 'https://github.com/zippoxer/subtask', github_owner: 'zippoxer', github_repo: 'subtask', description_en: 'Claude Skill to do your tasks with subagents in Git worktrees.', category_id: 'productivity', tags: ['skill', 'agent', 'productivity'], stars: 300 },
  { slug: 'blader-napkin', name: 'Napkin', name_ko: 'Napkin', github_url: 'https://github.com/blader/napkin', github_owner: 'blader', github_repo: 'napkin', description_en: 'Claude Code skill for persistent memory of agent mistakes via per-repo markdown scratchpad.', category_id: 'productivity', tags: ['skill', 'memory', 'productivity'], stars: 296 },
  { slug: 'komal-skynet-claude-skill-homeassistant', name: 'Home Assistant Skill', name_ko: 'Home Assistant 스킬', github_url: 'https://github.com/komal-SkyNET/claude-skill-homeassistant', github_owner: 'komal-SkyNET', github_repo: 'claude-skill-homeassistant', description_en: 'Claude Code skill to manage all Home Assistant workflows.', category_id: 'productivity', tags: ['skill', 'automation', 'productivity'], stars: 286 },
  { slug: 'lijigang-ljg-skill-xray-book', name: 'Book X-Ray', name_ko: '도서 X-Ray', github_url: 'https://github.com/lijigang/ljg-skill-xray-book', github_owner: 'lijigang', github_repo: 'ljg-skill-xray-book', description_en: 'Deep Book Analyzer - Claude Code Skill for three-round cognitive compression of books.', category_id: 'docs', tags: ['skill', 'writing', 'productivity'], stars: 279 },
  { slug: 'ancoleman-ai-design-components', name: 'AI Design Components', name_ko: 'AI 디자인 컴포넌트', github_url: 'https://github.com/ancoleman/ai-design-components', github_owner: 'ancoleman', github_repo: 'ai-design-components', description_en: 'Comprehensive UI/UX and Backend component design skills for AI-assisted development.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 273 },
  { slug: 'peterfei-ai-agent-team', name: 'AI Agent Team', name_ko: 'AI 에이전트 팀', github_url: 'https://github.com/peterfei/ai-agent-team', github_owner: 'peterfei', github_repo: 'ai-agent-team', description_en: 'AI Agent Team with PM, frontend, backend dev, and test engineer roles.', category_id: 'productivity', tags: ['claude-code', 'agent', 'productivity'], stars: 270 },
  { slug: 'francyjglisboa-agent-skill-creator', name: 'Agent Skill Creator', name_ko: '에이전트 스킬 크리에이터', github_url: 'https://github.com/FrancyJGLisboa/agent-skill-creator', github_owner: 'FrancyJGLisboa', github_repo: 'agent-skill-creator', description_en: 'Meta-skill that teaches Claude Code to create complete agents with Claude Skills.', category_id: 'productivity', tags: ['skill', 'agent', 'productivity'], stars: 268 },
  { slug: 'a5c-ai-babysitter', name: 'Babysitter', name_ko: 'Babysitter', github_url: 'https://github.com/a5c-ai/babysitter', github_owner: 'a5c-ai', github_repo: 'babysitter', description_en: 'Babysitter enables Claude Code to manage sophisticated development workflows.', category_id: 'productivity', tags: ['claude-code', 'productivity', 'automation'], stars: 267 },
  { slug: 'chujianyun-skills', name: 'WuMing Skills', name_ko: 'WuMing 스킬', github_url: 'https://github.com/chujianyun/skills', github_owner: 'chujianyun', github_repo: 'skills', description_en: 'WuMing\'s Claude Skills collection.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 261 },
  { slug: 'memvid-claude-brain', name: 'Claude Brain', name_ko: 'Claude Brain', github_url: 'https://github.com/memvid/claude-brain', github_owner: 'memvid', github_repo: 'claude-brain', description_en: 'Give Claude Code photographic memory in one portable file.', category_id: 'productivity', tags: ['claude-code', 'memory', 'productivity'], stars: 259 },
  { slug: 'jiweiyeah-skills-manager', name: 'Skills Manager', name_ko: '스킬 매니저', github_url: 'https://github.com/jiweiyeah/Skills-Manager', github_owner: 'jiweiyeah', github_repo: 'Skills-Manager', description_en: 'Desktop application for managing skills across multiple AI coding assistants.', category_id: 'productivity', tags: ['skill', 'productivity', 'tool'], stars: 255 },
  { slug: 'coffeefuelbump-csv-data-summarizer-claude-skill', name: 'CSV Data Summarizer', name_ko: 'CSV 데이터 요약기', github_url: 'https://github.com/coffeefuelbump/csv-data-summarizer-claude-skill', github_owner: 'coffeefuelbump', github_repo: 'csv-data-summarizer-claude-skill', description_en: 'A Claude Skill that automatically analyzes uploaded CSV files.', category_id: 'productivity', tags: ['skill', 'data', 'productivity'], stars: 241 },
  { slug: 'michalparkola-tapestry-skills-for-claude-code', name: 'Tapestry Skills', name_ko: 'Tapestry 스킬', github_url: 'https://github.com/michalparkola/tapestry-skills-for-claude-code', github_owner: 'michalparkola', github_repo: 'tapestry-skills-for-claude-code', description_en: 'Claude Code skills to download articles, PDFs, YouTube video transcripts.', category_id: 'docs', tags: ['skill', 'writing', 'productivity'], stars: 239 },
  { slug: 'ntcoding-claude-skillz', name: 'Claude Skillz', name_ko: 'Claude Skillz', github_url: 'https://github.com/NTCoding/claude-skillz', github_owner: 'NTCoding', github_repo: 'claude-skillz', description_en: 'Claude skills for common, simple programming tasks.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 235 },
  { slug: 'leastbit-claude_skills_zh-cn', name: 'Claude Skills ZH-CN', name_ko: 'Claude 스킬 중국어', github_url: 'https://github.com/LeastBit/Claude_skills_zh-CN', github_owner: 'LeastBit', github_repo: 'Claude_skills_zh-CN', description_en: 'Chinese learning version of Anthropics official skills.', category_id: 'docs', tags: ['skill', 'writing', 'development'], stars: 209 },
  { slug: 'aaron-he-zhu-seo-geo-claude-skills', name: 'SEO GEO Skills', name_ko: 'SEO GEO 스킬', github_url: 'https://github.com/aaron-he-zhu/seo-geo-claude-skills', github_owner: 'aaron-he-zhu', github_repo: 'seo-geo-claude-skills', description_en: '20 SEO and GEO skills for Claude Code, Cursor, Codex, and 35+ AI agents.', category_id: 'productivity', tags: ['skill', 'marketing', 'productivity'], stars: 207 },
  { slug: 'zarazhangrui-youtube-to-ebook', name: 'YouTube to Ebook', name_ko: 'YouTube to Ebook', github_url: 'https://github.com/zarazhangrui/youtube-to-ebook', github_owner: 'zarazhangrui', github_repo: 'youtube-to-ebook', description_en: 'Claude skill for turning YouTube transcripts into EPUB ebooks.', category_id: 'docs', tags: ['skill', 'writing', 'video'], stars: 191 },
  { slug: 'jsonbored-claudepro-directory', name: 'ClaudePro Directory', name_ko: 'ClaudePro 디렉토리', github_url: 'https://github.com/JSONbored/claudepro-directory', github_owner: 'JSONbored', github_repo: 'claudepro-directory', description_en: 'Searchable collection of pre-built Claude configurations, MCP servers, and custom skills.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 184 },
  { slug: 'alonw0-web-asset-generator', name: 'Web Asset Generator', name_ko: '웹 에셋 생성기', github_url: 'https://github.com/alonw0/web-asset-generator', github_owner: 'alonw0', github_repo: 'web-asset-generator', description_en: 'Claude skill to generate favicons, app icons, and social media images.', category_id: 'development', tags: ['skill', 'web', 'development'], stars: 184 },
  { slug: 'yunshu0909-yunshu_skillshub', name: 'Yunshu Skills Hub', name_ko: 'Yunshu 스킬 허브', github_url: 'https://github.com/yunshu0909/yunshu_skillshub', github_owner: 'yunshu0909', github_repo: 'yunshu_skillshub', description_en: 'Curated Claude Code Skills collection for development and product management.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 182 },
  { slug: 'agricidaniel-claude-ads', name: 'Claude Ads', name_ko: 'Claude Ads', github_url: 'https://github.com/AgriciDaniel/claude-ads', github_owner: 'AgriciDaniel', github_repo: 'claude-ads', description_en: 'Comprehensive paid advertising audit and optimization skill for Claude Code.', category_id: 'productivity', tags: ['skill', 'marketing', 'productivity'], stars: 181 },
  { slug: 'athola-claude-night-market', name: 'Claude Night Market', name_ko: 'Claude 야시장', github_url: 'https://github.com/athola/claude-night-market', github_owner: 'athola', github_repo: 'claude-night-market', description_en: 'Marketplace repo for Claude Code Plugins from personal projects and workflows.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 173 },
  { slug: 'op7418-video-wrapper-skills', name: 'Video Wrapper Skills', name_ko: '비디오 래퍼 스킬', github_url: 'https://github.com/op7418/Video-Wrapper-Skills', github_owner: 'op7418', github_repo: 'Video-Wrapper-Skills', description_en: 'Claude Skill for adding variety show style visual effects to interview videos.', category_id: 'productivity', tags: ['skill', 'video', 'productivity'], stars: 173 },
  { slug: 'palkan-skills', name: 'Layered Rails Skills', name_ko: 'Layered Rails 스킬', github_url: 'https://github.com/palkan/skills', github_owner: 'palkan', github_repo: 'skills', description_en: 'Claude skills based on the Layered Rails book and beyond.', category_id: 'development', tags: ['skill', 'rails', 'development'], stars: 172 },
  { slug: 'spences10-svelte-claude-skills', name: 'Svelte Claude Skills', name_ko: 'Svelte Claude 스킬', github_url: 'https://github.com/spences10/svelte-claude-skills', github_owner: 'spences10', github_repo: 'svelte-claude-skills', description_en: 'Svelte development skills for Claude Code.', category_id: 'development', tags: ['skill', 'svelte', 'development'], stars: 170 },
  { slug: 'zxkane-aws-skills', name: 'AWS Skills', name_ko: 'AWS 스킬', github_url: 'https://github.com/zxkane/aws-skills', github_owner: 'zxkane', github_repo: 'aws-skills', description_en: 'Claude Agent Skills for AWS cloud development and operations.', category_id: 'devops', tags: ['skill', 'aws', 'development'], stars: 165 },
  { slug: 'lijigang-ljg-explain-concept', name: 'Explain Concept', name_ko: '개념 해부기', github_url: 'https://github.com/lijigang/ljg-explain-concept', github_owner: 'lijigang', github_repo: 'ljg-explain-concept', description_en: 'Claude Code skill: 8-dimensional concept anatomist for deconstructing any concept.', category_id: 'docs', tags: ['skill', 'writing', 'productivity'], stars: 165 },
  { slug: 'aiskillstore-marketplace', name: 'AI Skill Store', name_ko: 'AI 스킬 스토어', github_url: 'https://github.com/aiskillstore/marketplace', github_owner: 'aiskillstore', github_repo: 'marketplace', description_en: 'Security-audited skills for Claude, Codex and Claude Code.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 159 },
  { slug: 'wlzh-skills', name: 'WLZH Skills', name_ko: 'WLZH 스킬', github_url: 'https://github.com/wlzh/skills', github_owner: 'wlzh', github_repo: 'skills', description_en: 'Open-source Claude Code Skills collection for practical daily needs.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 159 },
  { slug: 'smallnest-goskills', name: 'GoSkills', name_ko: 'GoSkills', github_url: 'https://github.com/smallnest/goskills', github_owner: 'smallnest', github_repo: 'goskills', description_en: 'A tool supporting OpenAI and other LLMs with Claude Skills.', category_id: 'development', tags: ['skill', 'development', 'tool'], stars: 158 },
  { slug: 'forayconsulting-gemini_cli_skill', name: 'Gemini CLI Skill', name_ko: 'Gemini CLI 스킬', github_url: 'https://github.com/forayconsulting/gemini_cli_skill', github_owner: 'forayconsulting', github_repo: 'gemini_cli_skill', description_en: 'A Claude Code skill enabling Claude to use Gemini 3 Pro via Gemini CLI.', category_id: 'productivity', tags: ['skill', 'agent', 'productivity'], stars: 157 },
  { slug: 'geekjourneyx-ai-daily-skill', name: 'AI Daily Skill', name_ko: 'AI 데일리 스킬', github_url: 'https://github.com/geekjourneyx/ai-daily-skill', github_owner: 'geekjourneyx', github_repo: 'ai-daily-skill', description_en: 'AI News Daily - Claude Code Skill for daily AI news collection and analysis.', category_id: 'productivity', tags: ['skill', 'productivity', 'automation'], stars: 151 },
  { slug: 'everyinc-charlie-cfo-skill', name: 'Charlie CFO Skill', name_ko: 'Charlie CFO 스킬', github_url: 'https://github.com/EveryInc/charlie-cfo-skill', github_owner: 'EveryInc', github_repo: 'charlie-cfo-skill', description_en: 'Claude Code skill for bootstrapped CFO financial management.', category_id: 'productivity', tags: ['skill', 'productivity', 'automation'], stars: 146 },
  { slug: 'sundial-org-skills', name: 'Sundial Skills', name_ko: 'Sundial 스킬', github_url: 'https://github.com/sundial-org/skills', github_owner: 'sundial-org', github_repo: 'skills', description_en: 'Claude Code Skills collection from Sundial.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 142 },
  { slug: 'joeseesun-music-genre-finder', name: 'Music Genre Finder', name_ko: '음악 장르 검색', github_url: 'https://github.com/joeseesun/music-genre-finder', github_owner: 'joeseesun', github_repo: 'music-genre-finder', description_en: 'Intelligent music genre search with 5947 genres from RateYourMusic. Claude Code skill.', category_id: 'productivity', tags: ['skill', 'productivity', 'tool'], stars: 141 },
  { slug: 'drcathicks-learning-opportunities', name: 'Learning Opportunities', name_ko: '학습 기회', github_url: 'https://github.com/DrCatHicks/learning-opportunities', github_owner: 'DrCatHicks', github_repo: 'learning-opportunities', description_en: 'A Claude Code skill for deliberate skill development during AI-assisted coding.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 136 },
  { slug: 'harrymunro-nelson', name: 'Nelson', name_ko: 'Nelson', github_url: 'https://github.com/harrymunro/nelson', github_owner: 'harrymunro', github_repo: 'nelson', description_en: 'Coordinate agent teams in Claude Code using a Royal Navy inspired command structure.', category_id: 'productivity', tags: ['claude-code', 'agent', 'productivity'], stars: 135 },
  { slug: 'yizhiyanhua-ai-skills-updater', name: 'Skills Updater', name_ko: '스킬 업데이터', github_url: 'https://github.com/yizhiyanhua-ai/skills-updater', github_owner: 'yizhiyanhua-ai', github_repo: 'skills-updater', description_en: 'Manage, update, and discover Claude Code skills.', category_id: 'productivity', tags: ['skill', 'productivity', 'tool'], stars: 135 },
  { slug: 'distil-labs-distil-cli-skill', name: 'Distil CLI Skill', name_ko: 'Distil CLI 스킬', github_url: 'https://github.com/distil-labs/distil-cli-skill', github_owner: 'distil-labs', github_repo: 'distil-cli-skill', description_en: 'Claude skill for Distil CLI integration.', category_id: 'development', tags: ['skill', 'development', 'tool'], stars: 131 },
  { slug: 'feiskyer-codex-settings', name: 'Codex Settings', name_ko: 'Codex 설정', github_url: 'https://github.com/feiskyer/codex-settings', github_owner: 'feiskyer', github_repo: 'codex-settings', description_en: 'OpenAI Codex CLI settings, configurations, skills and prompts for vibe coding.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 130 },
  { slug: 'microck-ordinary-claude-skills', name: 'Ordinary Claude Skills', name_ko: 'Ordinary Claude 스킬', github_url: 'https://github.com/Microck/ordinary-claude-skills', github_owner: 'Microck', github_repo: 'ordinary-claude-skills', description_en: 'Collection of Claude Skills and resources.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 124 },
  { slug: 'gbsoss--mcp-to-skill-converter', name: 'MCP to Skill Converter', name_ko: 'MCP to Skill 변환기', github_url: 'https://github.com/GBSOSS/-mcp-to-skill-converter', github_owner: 'GBSOSS', github_repo: '-mcp-to-skill-converter', description_en: 'Convert any MCP server into a Claude Skill with 90% context savings.', category_id: 'productivity', tags: ['skill', 'productivity', 'tool'], stars: 122 },
  { slug: 'cameronfreer-lean4-skills', name: 'Lean4 Skills', name_ko: 'Lean4 스킬', github_url: 'https://github.com/cameronfreer/lean4-skills', github_owner: 'cameronfreer', github_repo: 'lean4-skills', description_en: 'Claude skills for Lean 4 theorem proving.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 122 },
  { slug: 'honnibal-claude-skills', name: 'Honnibal Claude Skills', name_ko: 'Honnibal Claude 스킬', github_url: 'https://github.com/honnibal/claude-skills', github_owner: 'honnibal', github_repo: 'claude-skills', description_en: 'Experimental Claude skills collection.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 122 },
  { slug: 'wirasm-worktree-manager-skill', name: 'Worktree Manager Skill', name_ko: 'Worktree 매니저 스킬', github_url: 'https://github.com/Wirasm/worktree-manager-skill', github_owner: 'Wirasm', github_repo: 'worktree-manager-skill', description_en: 'A Claude Code skill for effortless Git worktree management.', category_id: 'productivity', tags: ['skill', 'productivity', 'tool'], stars: 121 },
  { slug: 'molefrog-skills', name: 'React PDF Skills', name_ko: 'React PDF 스킬', github_url: 'https://github.com/molefrog/skills', github_owner: 'molefrog', github_repo: 'skills', description_en: 'Claude skill for generating high-quality PDFs using react-pdf.', category_id: 'development', tags: ['skill', 'pdf', 'development'], stars: 118 },
  { slug: 'wondelai-skills', name: 'Wondelai Skills', name_ko: 'Wondelai 스킬', github_url: 'https://github.com/wondelai/skills', github_owner: 'wondelai', github_repo: 'skills', description_en: 'Agent skills for Claude Code and agentskills.io-compatible agents.', category_id: 'development', tags: ['skill', 'agent', 'development'], stars: 117 },
  { slug: 'staruhub-claudeskills', name: 'Staru Claude Skills', name_ko: 'Staru Claude 스킬', github_url: 'https://github.com/staruhub/ClaudeSkills', github_owner: 'staruhub', github_repo: 'ClaudeSkills', description_en: 'Sharing on Claude Skills collection.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 116 },
  { slug: 'chrisvoncsefalvay-claude-d3js-skill', name: 'D3.js Skill', name_ko: 'D3.js 스킬', github_url: 'https://github.com/chrisvoncsefalvay/claude-d3js-skill', github_owner: 'chrisvoncsefalvay', github_repo: 'claude-d3js-skill', description_en: 'A Claude skill for d3.js data visualization.', category_id: 'development', tags: ['skill', 'web', 'development'], stars: 113 },
  { slug: 'jthack-ffuf_claude_skill', name: 'FFUF Claude Skill', name_ko: 'FFUF Claude 스킬', github_url: 'https://github.com/jthack/ffuf_claude_skill', github_owner: 'jthack', github_repo: 'ffuf_claude_skill', description_en: 'A skill for Claude to use FFUF web fuzzer for security testing.', category_id: 'testing', tags: ['skill', 'security', 'development'], stars: 113 },
  { slug: 'jduncan-rva-skill-porter', name: 'Skill Porter', name_ko: 'Skill Porter', github_url: 'https://github.com/jduncan-rva/skill-porter', github_owner: 'jduncan-rva', github_repo: 'skill-porter', description_en: 'Universal tool to convert Claude Code skills to Gemini CLI extensions and vice versa.', category_id: 'productivity', tags: ['skill', 'productivity', 'tool'], stars: 112 },
  { slug: 'deanpeters-product-manager-skills', name: 'Product Manager Skills', name_ko: '프로덕트 매니저 스킬', github_url: 'https://github.com/deanpeters/Product-Manager-Skills', github_owner: 'deanpeters', github_repo: 'Product-Manager-Skills', description_en: 'Product Management skills framework built on battle-tested methods for Claude Code.', category_id: 'productivity', tags: ['skill', 'productivity', 'automation'], stars: 111 },
  { slug: 'posit-dev-skills', name: 'Posit Skills', name_ko: 'Posit 스킬', github_url: 'https://github.com/posit-dev/skills', github_owner: 'posit-dev', github_repo: 'skills', description_en: 'A collection of Claude Skills from Posit for R and data science.', category_id: 'development', tags: ['skill', 'data', 'development'], stars: 111 },
  { slug: 'giuseppe-trisciuoglio-developer-kit', name: 'Developer Kit', name_ko: 'Developer Kit', github_url: 'https://github.com/giuseppe-trisciuoglio/developer-kit', github_owner: 'giuseppe-trisciuoglio', github_repo: 'developer-kit', description_en: 'Developer Kit for Claude Code - a modular plugin system with reusable skills and agents.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 101 },
  { slug: 'prefecthq-colin', name: 'Colin', name_ko: 'Colin', github_url: 'https://github.com/PrefectHQ/colin', github_owner: 'PrefectHQ', github_repo: 'colin', description_en: 'A context engine that treats skills as software. From the Prefect team.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 101 },
  { slug: 'kangarooking-x-skills', name: 'X Skills', name_ko: 'X 스킬', github_url: 'https://github.com/kangarooking/x-skills', github_owner: 'kangarooking', github_repo: 'x-skills', description_en: 'Auto-collect materials, confirm topics, create and publish X tweets. Claude Skills.', category_id: 'productivity', tags: ['skill', 'automation', 'productivity'], stars: 99 },
  { slug: 'kyure-a-agent-skills-nix', name: 'Agent Skills Nix', name_ko: 'Agent Skills Nix', github_url: 'https://github.com/Kyure-A/agent-skills-nix', github_owner: 'Kyure-A', github_repo: 'agent-skills-nix', description_en: 'Declarative management of Agent Skills on Nix.', category_id: 'devops', tags: ['skill', 'nix', 'development'], stars: 98 },
  { slug: 'anombyte93-prd-taskmaster', name: 'PRD Taskmaster', name_ko: 'PRD Taskmaster', github_url: 'https://github.com/anombyte93/prd-taskmaster', github_owner: 'anombyte93', github_repo: 'prd-taskmaster', description_en: 'AI-powered PRD generation for Claude Code with taskmaster integration.', category_id: 'productivity', tags: ['skill', 'productivity', 'automation'], stars: 98 },
  { slug: 'wwwzhouhui-skills_collection', name: 'Skills Collection', name_ko: '스킬 컬렉션', github_url: 'https://github.com/wwwzhouhui/skills_collection', github_owner: 'wwwzhouhui', github_repo: 'skills_collection', description_en: 'Personal Claude Code Skills collection with practical tools.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 98 },
  { slug: 'greekr4-playwright-bot-bypass', name: 'Playwright Bot Bypass', name_ko: 'Playwright Bot Bypass', github_url: 'https://github.com/greekr4/playwright-bot-bypass', github_owner: 'greekr4', github_repo: 'playwright-bot-bypass', description_en: 'Claude Code skill to bypass bot detection (Google CAPTCHA, etc.)', category_id: 'testing', tags: ['skill', 'web', 'security'], stars: 97 },
  { slug: 'zaferayan-skills', name: 'Expo Dev Skill', name_ko: 'Expo 개발 스킬', github_url: 'https://github.com/zaferayan/skills', github_owner: 'zaferayan', github_repo: 'skills', description_en: 'Expo mobile app development skill for Claude Code.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 96 },
  { slug: 'adaptyvbio-protein-design-skills', name: 'Protein Design Skills', name_ko: '단백질 설계 스킬', github_url: 'https://github.com/adaptyvbio/protein-design-skills', github_owner: 'adaptyvbio', github_repo: 'protein-design-skills', description_en: 'Claude Code skills for protein design and bioinformatics.', category_id: 'other', tags: ['skill', 'development', 'productivity'], stars: 96 },
  { slug: 'kkoppenhaver-cc-nano-banana', name: 'CC Nano Banana', name_ko: 'CC Nano Banana', github_url: 'https://github.com/kkoppenhaver/cc-nano-banana', github_owner: 'kkoppenhaver', github_repo: 'cc-nano-banana', description_en: 'A Claude Code skill to generate images with Nano Banana.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 95 },
  { slug: 'pleaseprompto-google-ai-mode-skill', name: 'Google AI Mode Skill', name_ko: 'Google AI Mode 스킬', github_url: 'https://github.com/PleasePrompto/google-ai-mode-skill', github_owner: 'PleasePrompto', github_repo: 'google-ai-mode-skill', description_en: 'Claude Code skill for free Google AI Mode search with citations.', category_id: 'productivity', tags: ['skill', 'productivity', 'web'], stars: 94 },
  { slug: 'axiaoge2-apple-hig-designer', name: 'Apple HIG Designer', name_ko: 'Apple HIG 디자이너', github_url: 'https://github.com/axiaoge2/Apple-Hig-Designer', github_owner: 'axiaoge2', github_repo: 'Apple-Hig-Designer', description_en: 'Claude Code Skill for designing interfaces following Apple Human Interface Guidelines.', category_id: 'development', tags: ['skill', 'ios', 'development'], stars: 93 },
  { slug: 'kaichen-amap-skill', name: 'AMap Skill', name_ko: 'AMap 스킬', github_url: 'https://github.com/kaichen/amap-skill', github_owner: 'kaichen', github_repo: 'amap-skill', description_en: 'Claude Code skill for AMap (Gaode Map) Web Service API.', category_id: 'development', tags: ['skill', 'web', 'development'], stars: 87 },
  { slug: 'p4nda0s-reverse-skills', name: 'Reverse Skills', name_ko: '리버스 엔지니어링 스킬', github_url: 'https://github.com/P4nda0s/reverse-skills', github_owner: 'P4nda0s', github_repo: 'reverse-skills', description_en: 'Reverse engineering skills for Claude Code.', category_id: 'testing', tags: ['skill', 'reverse-engineering', 'security'], stars: 87 },
  { slug: 'huangjia2019-claude-code-engingeering', name: 'Claude Code Engineering', name_ko: 'Claude Code 엔지니어링', github_url: 'https://github.com/huangjia2019/claude-code-engingeering', github_owner: 'huangjia2019', github_repo: 'claude-code-engingeering', description_en: 'Using Claude Code to do real engineering work with practical examples.', category_id: 'development', tags: ['claude-code', 'development', 'productivity'], stars: 86 },
  { slug: 'ruya-ai-cozempic', name: 'Cozempic', name_ko: 'Cozempic', github_url: 'https://github.com/Ruya-AI/cozempic', github_owner: 'Ruya-AI', github_repo: 'cozempic', description_en: 'Context cleaning for Claude Code. Prune bloated sessions, protect agents from context loss.', category_id: 'productivity', tags: ['claude-code', 'productivity', 'tool'], stars: 84 },
  { slug: 'simoneavogadro-android-reverse-engineering-skill', name: 'Android RE Skill', name_ko: 'Android 리버스 엔지니어링 스킬', github_url: 'https://github.com/SimoneAvogadro/android-reverse-engineering-skill', github_owner: 'SimoneAvogadro', github_repo: 'android-reverse-engineering-skill', description_en: 'Claude Code skill for Android app reverse engineering.', category_id: 'testing', tags: ['skill', 'android', 'reverse-engineering'], stars: 83 },
  { slug: 'majiayu000-claude-skill-registry', name: 'Claude Skill Registry', name_ko: 'Claude 스킬 레지스트리', github_url: 'https://github.com/majiayu000/claude-skill-registry', github_owner: 'majiayu000', github_repo: 'claude-skill-registry', description_en: 'Comprehensive Claude Code skills registry.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 83 },
  { slug: 'adrianpuiu-claude-skills-marketplace', name: 'Project Architect Skill', name_ko: '프로젝트 아키텍트 스킬', github_url: 'https://github.com/adrianpuiu/claude-skills-marketplace', github_owner: 'adrianpuiu', github_repo: 'claude-skills-marketplace', description_en: 'A skill that establishes Claude as a Project Architect for structured development.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 82 },
  { slug: 'wshuyi-remotion-video-skill', name: 'Remotion Video Skill', name_ko: 'Remotion 비디오 스킬', github_url: 'https://github.com/wshuyi/remotion-video-skill', github_owner: 'wshuyi', github_repo: 'remotion-video-skill', description_en: 'A Claude Code Skill for creating programmatic videos with Remotion framework.', category_id: 'development', tags: ['skill', 'video', 'development'], stars: 80 },
  { slug: 'nbashaw-claude-cs', name: 'Claude CS', name_ko: 'Claude CS', github_url: 'https://github.com/nbashaw/claude-cs', github_owner: 'nbashaw', github_repo: 'claude-cs', description_en: 'Claude Code skill for building custom customer support automation.', category_id: 'productivity', tags: ['skill', 'automation', 'productivity'], stars: 80 },
  { slug: 'gapmiss-obsidian-plugin-skill', name: 'Obsidian Plugin Skill', name_ko: 'Obsidian 플러그인 스킬', github_url: 'https://github.com/gapmiss/obsidian-plugin-skill', github_owner: 'gapmiss', github_repo: 'obsidian-plugin-skill', description_en: 'Claude Skill for Obsidian.md plugin development.', category_id: 'development', tags: ['skill', 'obsidian', 'development'], stars: 78 },
  { slug: 'elvismdev-claude-wordpress-skills', name: 'WordPress Skills', name_ko: 'WordPress 스킬', github_url: 'https://github.com/elvismdev/claude-wordpress-skills', github_owner: 'elvismdev', github_repo: 'claude-wordpress-skills', description_en: 'Professional WordPress engineering skills for Claude Code.', category_id: 'development', tags: ['skill', 'wordpress', 'development'], stars: 78 },
  { slug: 'weaverse--claude', name: 'Weaverse Claude', name_ko: 'Weaverse Claude', github_url: 'https://github.com/Weaverse/.claude', github_owner: 'Weaverse', github_repo: '.claude', description_en: 'Claude Code skills, agents, and commands for daily development workflows.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 76 },
  { slug: 'ognjengt-founder-skills', name: 'Founder Skills', name_ko: 'Founder 스킬', github_url: 'https://github.com/ognjengt/founder-skills', github_owner: 'ognjengt', github_repo: 'founder-skills', description_en: 'Claude skills for founders and startup builders.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 74 },
  { slug: 'spences10-claude-skills-cli', name: 'Claude Skills CLI', name_ko: 'Claude Skills CLI', github_url: 'https://github.com/spences10/claude-skills-cli', github_owner: 'spences10', github_repo: 'claude-skills-cli', description_en: 'CLI for creating Claude Agent Skills with progressive disclosure validation.', category_id: 'productivity', tags: ['skill', 'productivity', 'tool'], stars: 74 },
  { slug: 'sanshao85-claude-skills-guide', name: 'Claude Skills Guide', name_ko: 'Claude Skills 가이드', github_url: 'https://github.com/sanshao85/claude-skills-guide', github_owner: 'sanshao85', github_repo: 'claude-skills-guide', description_en: 'Claude Skills complete development guide from basics to mastery.', category_id: 'docs', tags: ['skill', 'writing', 'development'], stars: 72 },
  { slug: 'dicklesworthstone-jeffreysprompts.com', name: 'Jeffreys Prompts', name_ko: 'Jeffreys Prompts', github_url: 'https://github.com/Dicklesworthstone/jeffreysprompts.com', github_owner: 'Dicklesworthstone', github_repo: 'jeffreysprompts.com', description_en: 'Curated battle-tested prompts for agentic coding. Browse, copy, install as Claude Skills.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 70 },
  { slug: 'coleam00-custom-agent-with-skills', name: 'Custom Agent With Skills', name_ko: 'Custom Agent With Skills', github_url: 'https://github.com/coleam00/custom-agent-with-skills', github_owner: 'coleam00', github_repo: 'custom-agent-with-skills', description_en: 'Pydantic AI agent implementing the idea of Claude Skills.', category_id: 'development', tags: ['skill', 'agent', 'development'], stars: 70 },
  { slug: 'nikolay-shirokov-cc-1c-skills', name: '1C Enterprise Skills', name_ko: '1C Enterprise 스킬', github_url: 'https://github.com/Nikolay-Shirokov/cc-1c-skills', github_owner: 'Nikolay-Shirokov', github_repo: 'cc-1c-skills', description_en: 'Claude Code skills for 1C:Enterprise development.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 66 },
  { slug: 'shpigford-skills', name: 'Shpigford Skills', name_ko: 'Shpigford 스킬', github_url: 'https://github.com/Shpigford/skills', github_owner: 'Shpigford', github_repo: 'skills', description_en: 'Claude Code skills for common tasks.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 65 },
  { slug: 'dontbesilent2025-extract-getnote-articles', name: 'GetNote Extractor', name_ko: 'GetNote 추출기', github_url: 'https://github.com/dontbesilent2025/extract-getnote-articles', github_owner: 'dontbesilent2025', github_repo: 'extract-getnote-articles', description_en: 'Claude Code Skill for auto-extracting articles from GetNote knowledge base.', category_id: 'docs', tags: ['skill', 'writing', 'productivity'], stars: 65 },
  { slug: 'jamesrochabrun-skills', name: 'JR Skills', name_ko: 'JR 스킬', github_url: 'https://github.com/jamesrochabrun/skills', github_owner: 'jamesrochabrun', github_repo: 'skills', description_en: 'Claude Code Skills collection.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 64 },
  { slug: 'ceeon-writing-assistant-skill', name: 'Writing Assistant Skill', name_ko: '자미디어 글쓰기 어시스턴트', github_url: 'https://github.com/Ceeon/writing-assistant-skill', github_owner: 'Ceeon', github_repo: 'writing-assistant-skill', description_en: 'Self-media writing interactive assistant - Claude Code Skill.', category_id: 'docs', tags: ['skill', 'writing', 'productivity'], stars: 64 },
  { slug: 'shikajiro-claude-code-skill-example', name: 'Skill Example', name_ko: '스킬 예제', github_url: 'https://github.com/shikajiro/claude-code-skill-example', github_owner: 'shikajiro', github_repo: 'claude-code-skill-example', description_en: 'Sample of Claude Code Skills usage and patterns.', category_id: 'docs', tags: ['skill', 'development', 'productivity'], stars: 64 },
  { slug: 'maquina-app-rails-upgrade-skill', name: 'Rails Upgrade Skill', name_ko: 'Rails 업그레이드 스킬', github_url: 'https://github.com/maquina-app/rails-upgrade-skill', github_owner: 'maquina-app', github_repo: 'rails-upgrade-skill', description_en: 'Claude Skill to upgrade a Rails application.', category_id: 'development', tags: ['skill', 'rails', 'development'], stars: 64 },
  { slug: 'haddock-development-claude-reflect-system', name: 'Claude Reflect System', name_ko: 'Claude Reflect System', github_url: 'https://github.com/haddock-development/claude-reflect-system', github_owner: 'haddock-development', github_repo: 'claude-reflect-system', description_en: 'Continual learning and self-improving skills system for Claude Code.', category_id: 'productivity', tags: ['skill', 'memory', 'productivity'], stars: 63 },
  { slug: 'aofp-yume', name: 'Yume', name_ko: 'Yume', github_url: 'https://github.com/aofp/yume', github_owner: 'aofp', github_repo: 'yume', description_en: 'Native desktop UI for Claude Code with orchestration and streaming.', category_id: 'productivity', tags: ['claude-code', 'productivity', 'tool'], stars: 63 },
  { slug: 'ark0n-claudeman', name: 'Claudeman', name_ko: 'Claudeman', github_url: 'https://github.com/Ark0N/Claudeman', github_owner: 'Ark0N', github_repo: 'Claudeman', description_en: 'Manage Claude Code in Tmux Sessions in a modern WebUI.', category_id: 'productivity', tags: ['claude-code', 'productivity', 'tool'], stars: 63 },
  { slug: 'aaronjmars-soul.md', name: 'Soul MD', name_ko: 'Soul MD', github_url: 'https://github.com/aaronjmars/soul.md', github_owner: 'aaronjmars', github_repo: 'soul.md', description_en: 'The best way to build a personality for your agent.', category_id: 'productivity', tags: ['claude-code', 'agent', 'productivity'], stars: 63 },
  { slug: 'gaearon-woodshed', name: 'Woodshed', name_ko: 'Woodshed', github_url: 'https://github.com/gaearon/woodshed', github_owner: 'gaearon', github_repo: 'woodshed', description_en: 'Create, run, rate, and iterate on your Claude Skills.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 62 },
  { slug: 'oikon48-cc-frontend-skills', name: 'CC Frontend Skills', name_ko: 'CC 프론트엔드 스킬', github_url: 'https://github.com/oikon48/cc-frontend-skills', github_owner: 'oikon48', github_repo: 'cc-frontend-skills', description_en: 'Claude Code plugin for creating frontend UIs that avoid generic AI aesthetics.', category_id: 'development', tags: ['claude-code', 'web', 'development'], stars: 61 },
  { slug: 'weizhena-deep-research-skills', name: 'Deep Research Skills', name_ko: 'Deep Research 스킬', github_url: 'https://github.com/Weizhena/Deep-Research-skills', github_owner: 'Weizhena', github_repo: 'Deep-Research-skills', description_en: 'Structured deep research skill for Claude Code with human-in-the-loop control.', category_id: 'productivity', tags: ['skill', 'productivity', 'automation'], stars: 60 },
  { slug: 'dennisonbertram-steal-react-component', name: 'Steal React Component', name_ko: 'React 컴포넌트 추출기', github_url: 'https://github.com/dennisonbertram/steal-react-component', github_owner: 'dennisonbertram', github_repo: 'steal-react-component', description_en: 'Claude Code skill to extract React components from any production website.', category_id: 'development', tags: ['skill', 'react', 'web'], stars: 59 },
  { slug: 'dianel555-dskills', name: 'DSkills', name_ko: 'DSkills', github_url: 'https://github.com/Dianel555/DSkills', github_owner: 'Dianel555', github_repo: 'DSkills', description_en: 'CLI tools skills for AI coding assistants (Claude Code, Codex, Gemini CLI).', category_id: 'development', tags: ['skill', 'development', 'tool'], stars: 57 },
  { slug: 'ai-unleashed-claude-skills', name: 'AI Unleashed Skills', name_ko: 'AI Unleashed 스킬', github_url: 'https://github.com/AI-Unleashed/Claude-Skills', github_owner: 'AI-Unleashed', github_repo: 'Claude-Skills', description_en: 'Claude Code skills including autoskill - a meta-skill that learns from corrections.', category_id: 'productivity', tags: ['skill', 'memory', 'productivity'], stars: 57 },
  { slug: 'mikemaccana-solana-anchor-claude-skill', name: 'Solana Anchor Skill', name_ko: 'Solana Anchor 스킬', github_url: 'https://github.com/mikemaccana/solana-anchor-claude-skill', github_owner: 'mikemaccana', github_repo: 'solana-anchor-claude-skill', description_en: 'The Solana and Anchor Claude skill for blockchain development.', category_id: 'development', tags: ['skill', 'solana', 'development'], stars: 57 },
  { slug: 'jshchnz-claude-jobs', name: 'Claude Jobs', name_ko: 'Claude Jobs', github_url: 'https://github.com/jshchnz/claude-jobs', github_owner: 'jshchnz', github_repo: 'claude-jobs', description_en: 'Claude Code skill for querying job openings at tech companies.', category_id: 'productivity', tags: ['skill', 'productivity', 'tool'], stars: 54 },
  { slug: 'secondsky-claude-skills', name: 'Secondsky Claude Skills', name_ko: 'Secondsky Claude 스킬', github_url: 'https://github.com/secondsky/claude-skills', github_owner: 'secondsky', github_repo: 'claude-skills', description_en: 'Production-ready skills for Claude Code CLI - Cloudflare, React, Tailwind v4.', category_id: 'development', tags: ['skill', 'react', 'web'], stars: 53 },
  { slug: 'danielchu97-value-investing-agent', name: 'Value Investing Agent', name_ko: '가치 투자 에이전트', github_url: 'https://github.com/danielchu97/Value-Investing-Agent', github_owner: 'danielchu97', github_repo: 'Value-Investing-Agent', description_en: 'AI value investing agent. Analyze stocks like Graham and Buffett.', category_id: 'productivity', tags: ['skill', 'productivity', 'automation'], stars: 53 },
  { slug: 'altimateai-data-engineering-skills', name: 'Data Engineering Skills', name_ko: '데이터 엔지니어링 스킬', github_url: 'https://github.com/AltimateAI/data-engineering-skills', github_owner: 'AltimateAI', github_repo: 'data-engineering-skills', description_en: 'Skills related to Data Engineering Work for Claude Code.', category_id: 'development', tags: ['skill', 'data', 'development'], stars: 53 },
  { slug: 'artemxtech-personal-os-skills', name: 'Personal OS Skills', name_ko: 'Personal OS 스킬', github_url: 'https://github.com/ArtemXTech/personal-os-skills', github_owner: 'ArtemXTech', github_repo: 'personal-os-skills', description_en: 'Claude Code skills for Obsidian personal OS workflow.', category_id: 'productivity', tags: ['skill', 'obsidian', 'productivity'], stars: 53 },
  { slug: 'serpro69-claude-starter-kit', name: 'Claude Starter Kit', name_ko: 'Claude Starter Kit', github_url: 'https://github.com/serpro69/claude-starter-kit', github_owner: 'serpro69', github_repo: 'claude-starter-kit', description_en: 'Starter template repo for Claude Code configs, skills, agents and more.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 52 },
  { slug: 'athola-skrills', name: 'Skrills', name_ko: 'Skrills', github_url: 'https://github.com/athola/skrills', github_owner: 'athola', github_repo: 'skrills', description_en: 'Coordinate skills between Codex, Copilot, and Claude Code.', category_id: 'productivity', tags: ['skill', 'productivity', 'tool'], stars: 52 },
  { slug: 'leemysw-feishu-docx', name: 'Feishu Docx', name_ko: 'Feishu Docx', github_url: 'https://github.com/leemysw/feishu-docx', github_owner: 'leemysw', github_repo: 'feishu-docx', description_en: 'Feishu/Lark Docs, Sheet, Bitable to Markdown. AI Agent-friendly knowledge base exporter.', category_id: 'docs', tags: ['skill', 'writing', 'productivity'], stars: 52 },
  { slug: 'jackculpan-claude-skills-curated', name: 'Claude Skills Curated', name_ko: 'Claude Skills Curated', github_url: 'https://github.com/jackculpan/claude-skills-curated', github_owner: 'jackculpan', github_repo: 'claude-skills-curated', description_en: 'Hand-picked collection of the best Claude Code skills, plugins, and resources.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 52 },
  { slug: 'wrsmith108-linear-claude-skill', name: 'Linear Claude Skill', name_ko: 'Linear Claude 스킬', github_url: 'https://github.com/wrsmith108/linear-claude-skill', github_owner: 'wrsmith108', github_repo: 'linear-claude-skill', description_en: 'Claude Code skill for managing Linear issues, projects, and teams.', category_id: 'productivity', tags: ['skill', 'productivity', 'automation'], stars: 51 },
  { slug: 'highmark-31-trae-skills', name: 'TRAE Skills', name_ko: 'TRAE Skills', github_url: 'https://github.com/HighMark-31/TRAE-Skills', github_owner: 'HighMark-31', github_repo: 'TRAE-Skills', description_en: 'Collection of 150+ specialized AI Skills for software development.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 51 },
  { slug: 'iamzifei-wechat-article-publisher-skill', name: 'WeChat Article Publisher', name_ko: 'WeChat 아티클 퍼블리셔', github_url: 'https://github.com/iamzifei/wechat-article-publisher-skill', github_owner: 'iamzifei', github_repo: 'wechat-article-publisher-skill', description_en: 'Claude Skill that publishes WeChat articles.', category_id: 'docs', tags: ['skill', 'wechat', 'writing'], stars: 51 },
  { slug: 'ypares-rigup.nix', name: 'Rigup Nix', name_ko: 'Rigup Nix', github_url: 'https://github.com/YPares/rigup.nix', github_owner: 'YPares', github_repo: 'rigup.nix', description_en: 'AI agents and Nix: parametrable skills and tools, packaged together.', category_id: 'devops', tags: ['skill', 'nix', 'agent'], stars: 50 },
  { slug: 'jjmartres-opencode', name: 'JJ Opencode', name_ko: 'JJ Opencode', github_url: 'https://github.com/jjmartres/opencode', github_owner: 'jjmartres', github_repo: 'opencode', description_en: 'Powerful custom opencode configuration with agents, commands, rules, and skills.', category_id: 'development', tags: ['claude-code', 'agent', 'development'], stars: 48 },
  { slug: 'shawhint-ai-tutor-skill', name: 'AI Tutor Skill', name_ko: 'AI 튜터 스킬', github_url: 'https://github.com/ShawhinT/ai-tutor-skill', github_owner: 'ShawhinT', github_repo: 'ai-tutor-skill', description_en: 'Example Claude skill for explaining technical AI concepts.', category_id: 'docs', tags: ['skill', 'writing', 'development'], stars: 48 },
  { slug: 'mensfeld-craftdesk', name: 'Craftdesk', name_ko: 'Craftdesk', github_url: 'https://github.com/mensfeld/craftdesk', github_owner: 'mensfeld', github_repo: 'craftdesk', description_en: 'Package manager for Claude Code skills and agents.', category_id: 'productivity', tags: ['skill', 'productivity', 'tool'], stars: 47 },
  { slug: 'secondsky-sap-skills', name: 'SAP Skills', name_ko: 'SAP 스킬', github_url: 'https://github.com/secondsky/sap-skills', github_owner: 'secondsky', github_repo: 'sap-skills', description_en: 'Production-ready Claude Code skills for SAP development - 35 skills covering BTP, CAP, Fiori.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 47 },
  { slug: 'qianjietech-open-claudeskill', name: 'Open ClaudeSkill', name_ko: 'Open ClaudeSkill', github_url: 'https://github.com/QianjieTech/Open-ClaudeSkill', github_owner: 'QianjieTech', github_repo: 'Open-ClaudeSkill', description_en: 'Bring Claude\'s Skill system to any MCP-compatible AI agent through progressive disclosure.', category_id: 'development', tags: ['skill', 'agent', 'development'], stars: 47 },
  { slug: 'sendaifun-skills', name: 'Sendai Solana Skills', name_ko: 'Sendai Solana 스킬', github_url: 'https://github.com/sendaifun/skills', github_owner: 'sendaifun', github_repo: 'skills', description_en: 'Public marketplace of Solana-related skills for agents.', category_id: 'development', tags: ['skill', 'solana', 'development'], stars: 46 },
  { slug: 'umairalipathan1980-claude-skill-for-full-stack-application-development', name: 'Full Stack App Skill', name_ko: '풀스택 앱 스킬', github_url: 'https://github.com/umairalipathan1980/Claude-Skill-for-Full-Stack-Application-Development', github_owner: 'umairalipathan1980', github_repo: 'Claude-Skill-for-Full-Stack-Application-Development', description_en: 'Custom Claude Skill for generating full-stack application templates.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 46 },
  { slug: 'kylehughes-the-unofficial-swift-concurrency-migration-skill', name: 'Swift Concurrency Migration', name_ko: 'Swift Concurrency 마이그레이션', github_url: 'https://github.com/kylehughes/the-unofficial-swift-concurrency-migration-skill', github_owner: 'kylehughes', github_repo: 'the-unofficial-swift-concurrency-migration-skill', description_en: 'The Swift Concurrency Migration Guide packaged as a Skill for LLMs.', category_id: 'development', tags: ['skill', 'ios', 'development'], stars: 45 },
  { slug: 'spillwavesolutions-project-memory', name: 'Project Memory', name_ko: 'Project Memory', github_url: 'https://github.com/SpillwaveSolutions/project-memory', github_owner: 'SpillwaveSolutions', github_repo: 'project-memory', description_en: 'A Claude skill for tracking project state and progress.', category_id: 'productivity', tags: ['skill', 'memory', 'productivity'], stars: 45 },
  { slug: 'asiaostrich-universal-dev-skills', name: 'Universal Dev Skills', name_ko: 'Universal Dev 스킬', github_url: 'https://github.com/AsiaOstrich/universal-dev-skills', github_owner: 'AsiaOstrich', github_repo: 'universal-dev-skills', description_en: 'Universal development standards for AI coding assistants.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 44 },
  { slug: 'b33eep-claude-code-setup', name: 'Claude Code Setup', name_ko: 'Claude Code Setup', github_url: 'https://github.com/b33eep/claude-code-setup', github_owner: 'b33eep', github_repo: 'claude-code-setup', description_en: 'Persistent memory system for Claude Code via Markdown.', category_id: 'productivity', tags: ['claude-code', 'memory', 'productivity'], stars: 44 },
  { slug: 'codenamev-ai-software-architect', name: 'AI Software Architect', name_ko: 'AI 소프트웨어 아키텍트', github_url: 'https://github.com/codenamev/ai-software-architect', github_owner: 'codenamev', github_repo: 'ai-software-architect', description_en: 'AI-powered architecture documentation framework with ADRs and reviews.', category_id: 'docs', tags: ['skill', 'writing', 'development'], stars: 44 },
  { slug: 'indianoldturtledove-claude-skill-authoring', name: 'Claude Skill Authoring', name_ko: 'Claude Skill Authoring', github_url: 'https://github.com/IndianOldTurtledove/claude-skill-authoring', github_owner: 'IndianOldTurtledove', github_repo: 'claude-skill-authoring', description_en: 'A Claude Code Skill for creating and validating Claude Code Skills.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 44 },
  { slug: 'cocoindex-io-cocoindex-claude', name: 'CocoIndex Claude', name_ko: 'CocoIndex Claude', github_url: 'https://github.com/cocoindex-io/cocoindex-claude', github_owner: 'cocoindex-io', github_repo: 'cocoindex-claude', description_en: 'CocoIndex Claude Code Skill for data indexing.', category_id: 'development', tags: ['skill', 'data', 'development'], stars: 42 },
  { slug: 'nesbo-dotnet-claude-code-skills', name: 'Dotnet Claude Skills', name_ko: '.NET Claude 스킬', github_url: 'https://github.com/nesbo/dotnet-claude-code-skills', github_owner: 'nesbo', github_repo: 'dotnet-claude-code-skills', description_en: 'Claude Code Skills for .NET developers.', category_id: 'development', tags: ['skill', 'dotnet', 'development'], stars: 42 },
  { slug: 'brownfinesecurity-picocom-claude-skill', name: 'Picocom Claude Skill', name_ko: 'Picocom Claude 스킬', github_url: 'https://github.com/BrownFineSecurity/picocom-claude-skill', github_owner: 'BrownFineSecurity', github_repo: 'picocom-claude-skill', description_en: 'A Claude Code skill for using picocom to access a live UART shell for hardware hacking.', category_id: 'testing', tags: ['skill', 'security', 'development'], stars: 42 },
  { slug: 'saskinosie-weaviate-claude-skills', name: 'Weaviate Claude Skills', name_ko: 'Weaviate Claude 스킬', github_url: 'https://github.com/saskinosie/weaviate-claude-skills', github_owner: 'saskinosie', github_repo: 'weaviate-claude-skills', description_en: 'Claude Skills for connecting to local Weaviate vector databases.', category_id: 'development', tags: ['skill', 'data', 'development'], stars: 41 },
  { slug: 'dean2021-mijia-device-manager', name: 'Mijia Device Manager', name_ko: 'Mijia 디바이스 매니저', github_url: 'https://github.com/dean2021/mijia-device-manager', github_owner: 'dean2021', github_repo: 'mijia-device-manager', description_en: 'Manage and control Xiaomi/Mijia smart home devices. Compatible with Claude Code.', category_id: 'productivity', tags: ['skill', 'automation', 'productivity'], stars: 40 },
  { slug: 'belumume-claude-skills', name: 'Belumume Claude Skills', name_ko: 'Belumume Claude 스킬', github_url: 'https://github.com/belumume/claude-skills', github_owner: 'belumume', github_repo: 'claude-skills', description_en: 'Personal collection of Claude skills for real-world problems.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 40 },
  { slug: 'harikrishna8121999-antigravity-workflows', name: 'Antigravity Workflows', name_ko: 'Antigravity Workflows', github_url: 'https://github.com/harikrishna8121999/antigravity-workflows', github_owner: 'harikrishna8121999', github_repo: 'antigravity-workflows', description_en: 'Community-driven workflows for Antigravity AI, reusable prompts and automation.', category_id: 'productivity', tags: ['skill', 'automation', 'productivity'], stars: 40 },
  { slug: 'blacktop-ipsw-skill', name: 'IPSW Skill', name_ko: 'IPSW 스킬', github_url: 'https://github.com/blacktop/ipsw-skill', github_owner: 'blacktop', github_repo: 'ipsw-skill', description_en: 'A SKILL.md for ipsw Apple security research tool.', category_id: 'testing', tags: ['skill', 'security', 'ios'], stars: 40 },
  { slug: 'dpconde-claude-android-skill', name: 'Claude Android Skill', name_ko: 'Claude Android 스킬', github_url: 'https://github.com/dpconde/claude-android-skill', github_owner: 'dpconde', github_repo: 'claude-android-skill', description_en: 'Claude Code skill for building modern Android apps following best practices.', category_id: 'development', tags: ['skill', 'android', 'development'], stars: 40 },
  { slug: 'kylehughes-the-unofficial-swift-programming-language-skill', name: 'Swift Language Skill', name_ko: 'Swift 언어 스킬', github_url: 'https://github.com/kylehughes/the-unofficial-swift-programming-language-skill', github_owner: 'kylehughes', github_repo: 'the-unofficial-swift-programming-language-skill', description_en: 'The Swift Programming Language packaged as a Skill for LLMs.', category_id: 'development', tags: ['skill', 'ios', 'development'], stars: 39 },
  { slug: 'thamjiahe-claude-prompt-engineering-guide', name: 'Prompt Engineering Guide', name_ko: '프롬프트 엔지니어링 가이드', github_url: 'https://github.com/ThamJiaHe/claude-prompt-engineering-guide', github_owner: 'ThamJiaHe', github_repo: 'claude-prompt-engineering-guide', description_en: 'Guide for writing professional Claude prompts with MCP, Skills, and Superpowers.', category_id: 'docs', tags: ['skill', 'writing', 'development'], stars: 39 },
  { slug: 'jordanrubin-future_tokens', name: 'Future Tokens', name_ko: 'Future Tokens', github_url: 'https://github.com/jordanrubin/FUTURE_TOKENS', github_owner: 'jordanrubin', github_repo: 'FUTURE_TOKENS', description_en: 'Composable reasoning skills for Claude - antithesize, excavate, metaphorize, synthesize.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 39 },
  { slug: 'sionic-ai-sionic-maestro-skills', name: 'Sionic Maestro Skills', name_ko: 'Sionic Maestro 스킬', github_url: 'https://github.com/sionic-ai/sionic-maestro-skills', github_owner: 'sionic-ai', github_repo: 'sionic-maestro-skills', description_en: 'Claude Code Skills for Centralized Consult architecture for multi-coding CLI.', category_id: 'development', tags: ['skill', 'agent', 'development'], stars: 39 },
  { slug: 'rfxlamia-claude-skillkit', name: 'Claude SkillKit', name_ko: 'Claude SkillKit', github_url: 'https://github.com/rfxlamia/claude-skillkit', github_owner: 'rfxlamia', github_repo: 'claude-skillkit', description_en: 'Claude Skill Kit that can build comprehensive skills based on research.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 39 },
  { slug: 'decebals-claude-code-java', name: 'Claude Code Java', name_ko: 'Claude Code Java', github_url: 'https://github.com/decebals/claude-code-java', github_owner: 'decebals', github_repo: 'claude-code-java', description_en: 'Reusable AI development infrastructure for Java projects optimized for Claude Code.', category_id: 'development', tags: ['skill', 'java', 'development'], stars: 38 },
  { slug: 'outlinedriven-outline-driven-development', name: 'Outline Driven Dev', name_ko: 'Outline Driven Dev', github_url: 'https://github.com/OutlineDriven/outline-driven-development', github_owner: 'OutlineDriven', github_repo: 'outline-driven-development', description_en: 'Outline Driven Development using AST analysis and Modern CLI Tools.', category_id: 'development', tags: ['claude-code', 'development', 'productivity'], stars: 37 },
  { slug: 'omidzamani-dspy-skills', name: 'DSPy Skills', name_ko: 'DSPy 스킬', github_url: 'https://github.com/OmidZamani/dspy-skills', github_owner: 'OmidZamani', github_repo: 'dspy-skills', description_en: 'Collection of Claude Skills for DSPy framework.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 37 },
  { slug: 'omkamal-pypict-claude-skill', name: 'PyPICT Claude Skill', name_ko: 'PyPICT Claude 스킬', github_url: 'https://github.com/omkamal/pypict-claude-skill', github_owner: 'omkamal', github_repo: 'pypict-claude-skill', description_en: 'A Claude skill to generate test cases using N-wise testing with pypict.', category_id: 'testing', tags: ['skill', 'development', 'tool'], stars: 37 },
  { slug: 'jefflester-claude-skills-supercharged', name: 'Skills Supercharged', name_ko: 'Skills Supercharged', github_url: 'https://github.com/jefflester/claude-skills-supercharged', github_owner: 'jefflester', github_repo: 'claude-skills-supercharged', description_en: 'Supercharged implementation of Claude Code Skills.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 37 },
  { slug: 'fvadicamo-dev-agent-skills', name: 'Dev Agent Skills', name_ko: 'Dev Agent 스킬', github_url: 'https://github.com/fvadicamo/dev-agent-skills', github_owner: 'fvadicamo', github_repo: 'dev-agent-skills', description_en: 'Claude Code skills plugin for Git, GitHub, and skill authoring workflows.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 36 },
  { slug: 'karanjot786-agent-skills-cli', name: 'Agent Skills CLI', name_ko: 'Agent Skills CLI', github_url: 'https://github.com/Karanjot786/agent-skills-cli', github_owner: 'Karanjot786', github_repo: 'agent-skills-cli', description_en: 'Universal CLI for Agent Skills. Access 40,000+ skills from SkillsMP.', category_id: 'productivity', tags: ['skill', 'productivity', 'tool'], stars: 36 },
  { slug: 'onewave-ai-claude-skills', name: 'OneWave Claude Skills', name_ko: 'OneWave Claude 스킬', github_url: 'https://github.com/OneWave-AI/claude-skills', github_owner: 'OneWave-AI', github_repo: 'claude-skills', description_en: '100 Production-Ready Claude Code Skills collection.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 36 },
  { slug: 'evolsb-claude-legal-skill', name: 'Claude Legal Skill', name_ko: 'Claude Legal 스킬', github_url: 'https://github.com/evolsb/claude-legal-skill', github_owner: 'evolsb', github_repo: 'claude-legal-skill', description_en: 'Claude Code skill for legal contract review - NDAs, SaaS agreements, M&A documents.', category_id: 'productivity', tags: ['skill', 'productivity', 'automation'], stars: 35 },
  { slug: 'artwist-polyakov-polyakov-claude-skills', name: 'Polyakov Claude Skills', name_ko: 'Polyakov Claude 스킬', github_url: 'https://github.com/artwist-polyakov/polyakov-claude-skills', github_owner: 'artwist-polyakov', github_repo: 'polyakov-claude-skills', description_en: 'Collection of Claude skills.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 35 },
  { slug: 'curiositech-some_claude_skills', name: 'Curiositech Skills', name_ko: 'Curiositech 스킬', github_url: 'https://github.com/curiositech/some_claude_skills', github_owner: 'curiositech', github_repo: 'some_claude_skills', description_en: 'Claude skills collection for daily productivity.', category_id: 'productivity', tags: ['skill', 'productivity', 'development'], stars: 35 },
  { slug: 'jamditis-claude-skills-journalism', name: 'Journalism Skills', name_ko: '저널리즘 스킬', github_url: 'https://github.com/jamditis/claude-skills-journalism', github_owner: 'jamditis', github_repo: 'claude-skills-journalism', description_en: 'Claude Code skills for journalism, media, and academia.', category_id: 'docs', tags: ['skill', 'writing', 'productivity'], stars: 35 },
  { slug: 'nanmicoder-claude-code-skills', name: 'NanmiCoder Skills', name_ko: 'NanmiCoder 스킬', github_url: 'https://github.com/NanmiCoder/claude-code-skills', github_owner: 'NanmiCoder', github_repo: 'claude-code-skills', description_en: 'Claude Code skills collection with slides-generator and more.', category_id: 'development', tags: ['skill', 'development', 'productivity'], stars: 34 },
  { slug: 'thoughtbot-rails-audit-thoughtbot', name: 'Rails Audit', name_ko: 'Rails Audit', github_url: 'https://github.com/thoughtbot/rails-audit-thoughtbot', github_owner: 'thoughtbot', github_repo: 'rails-audit-thoughtbot', description_en: 'Claude skill to run code audits on Rails applications.', category_id: 'testing', tags: ['skill', 'rails', 'development'], stars: 33 },
  { slug: 'ryanbbrown-revealjs-skill', name: 'Reveal.js Skill', name_ko: 'Reveal.js 스킬', github_url: 'https://github.com/ryanbbrown/revealjs-skill', github_owner: 'ryanbbrown', github_repo: 'revealjs-skill', description_en: 'Claude Code skill for making reveal.js presentations.', category_id: 'docs', tags: ['skill', 'web', 'development'], stars: 32 },
  { slug: 'mohitagw15856-pm-claude-skills', name: 'PM Claude Skills', name_ko: 'PM Claude 스킬', github_url: 'https://github.com/mohitagw15856/pm-claude-skills', github_owner: 'mohitagw15856', github_repo: 'pm-claude-skills', description_en: 'Product Management Skills for Claude AI saving 8-9 hours per week.', category_id: 'productivity', tags: ['skill', 'productivity', 'automation'], stars: 32 },
  { slug: 'sheeki03-few-word', name: 'Few Word', name_ko: 'Few Word', github_url: 'https://github.com/sheeki03/Few-Word', github_owner: 'sheeki03', github_repo: 'Few-Word', description_en: 'Claude Code plugin that offloads large outputs to filesystem and retrieves when required.', category_id: 'productivity', tags: ['claude-code', 'productivity', 'tool'], stars: 31 },
  { slug: 'saadshahd-moo.md', name: 'Moo MD', name_ko: 'Moo MD', github_url: 'https://github.com/saadshahd/moo.md', github_owner: 'saadshahd', github_repo: 'moo.md', description_en: 'Structured thinking for Claude Code - ask before building, search before writing, verify before shipping.', category_id: 'productivity', tags: ['claude-code', 'productivity', 'development'], stars: 30 },
];

async function main() {
  // Check existing
  const { data: existing } = await supabase
    .from('skills')
    .select('github_url');

  const existingUrls = new Set(existing?.map((s) => s.github_url) ?? []);

  const toInsert = newSkills.filter((s) => !existingUrls.has(s.github_url));
  console.log(`Total new skills: ${newSkills.length}`);
  console.log(`Already in DB: ${newSkills.length - toInsert.length}`);
  console.log(`To insert: ${toInsert.length}`);

  if (toInsert.length === 0) {
    console.log('Nothing to insert.');
    return;
  }

  let inserted = 0;
  let failed = 0;

  for (const skill of toInsert) {
    const { error } = await supabase.from('skills').insert({
      ...skill,
      tags: [...skill.tags],
    });

    if (error) {
      console.error(`  FAIL: ${skill.slug} — ${error.message}`);
      failed++;
    } else {
      console.log(`  OK: ${skill.slug}`);
      inserted++;
    }
  }

  console.log(`\n=== Done ===`);
  console.log(`  Inserted: ${inserted}`);
  console.log(`  Failed: ${failed}`);
  console.log(`\nNext: npx tsx scripts/enrich-skills.ts`);
}

main().catch(console.error);
